apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dalmus1/Minikube_charts_deployments 
    targetRevision: main
    path: alerting/apps/mimir-sync
  destination:
    server: https://kubernetes.default.svc
    namespace: alerting   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
